spring.application.name=sgs
spring.datasource.url=jdbc:postgresql://localhost:5432/sgs
spring.datasource.username=postgres
spring.datasource.password=2219897913Cs!

spring.datasource.driver-class-name=org.postgresql.Driver