-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.categoria
(
    id serial NOT NULL,
    nome character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT categoria_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.solicitacao
(
    id serial NOT NULL,
    solicitante_id serial NOT NULL,
    categoria_id serial NOT NULL,
    descricao character varying(200) COLLATE pg_catalog."default" NOT NULL,
    valor numeric(10, 2) NOT NULL,
    data_solicitacao date NOT NULL,
    status_id serial NOT NULL,
    CONSTRAINT solicitacao_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.solicitante
(
    id serial NOT NULL,
    nome character varying(200) COLLATE pg_catalog."default" NOT NULL,
    cpfcnpj character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT solicitante_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.status
(
    id serial NOT NULL,
    descricao character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT status_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.solicitacao
    ADD CONSTRAINT categoria_fk FOREIGN KEY (categoria_id)
    REFERENCES public.categoria (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.solicitacao
    ADD CONSTRAINT solicitante_fk FOREIGN KEY (solicitante_id)
    REFERENCES public.solicitante (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.solicitacao
    ADD CONSTRAINT status_fk FOREIGN KEY (status_id)
    REFERENCES public.status (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;